### ISSUE TITLE
Request: RSS Feed of New Songs

### ISSUE THREAD

**Issue by steets250** [Byorun/beatsaver-laravel#20]
It would be nice if there was a way to be notified of new songs. I find myself frequently checking the newest songs list. Having a feed of some sort would make it easier to monitor new content.

**Comment by elliotttate** [comment]
Until this gets added, you can use use the RSS feed feature on bsaber.com and it should do exactly what you were wanting. You can also subscribe using the Wordpress app or follow new songs using App News or Google News.

**Comment by Byorun** [comment]
RSS is a good idea, I need to evaluate compatible rss libs for php/laravel ( I am not going to implement RSS myself). My Rewrite included a discord webhook for every uploaded song (I don't know which channel it is currently configured at). This may be an alternative until rss is implemented. 
Also if anyone wants to do that, I am happy to help since I am too busy to implement completely new features right now

**Comment by Byorun** [comment]
will be added with #39
